### ISSUE TITLE
ownership for pluribus driver

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation/napalm-pluribus#44]
Hello,
community drivers are going to be maintained by the community or considered deprecated and unmaintained. For that reason we are looking for people willing to maintain this repo. Owners will have full admin rights on this repo and on its pypy package.

Pinging top contributors to see if they are interested; @mirceaulinic @fooelisa 
If you have questions/comments let me know.

Regards

**Comment by mirceaulinic** [comment]
Yep, I will take this on myself. Hope to be able to deal with the overwhelming amount of bug reports 😆
